using ExcelGenerate.DTO;
using ExcelGenerate.Extensions;
using ExcelGenerate.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExcelGenerate.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ExcelGenerateController : ControllerBase
    {
        private readonly IExcelGenerateService _excelGenerateService;
        public ExcelGenerateController(IExcelGenerateService excelGenerateService)
        {
            _excelGenerateService = excelGenerateService;
        }

        [HttpGet("GenerateExcel")]
        public async Task<IActionResult> GenerateExcel()
        {
            try
            {
                //var result = await _excelGenerateService.GenerateExcel(Utility.GenerateDatatableWithData(4, 3));


                var displayFields = new List<KeyValuePair<string, string>>()
                        {
                            new KeyValuePair<string,string>("TITLE_FIELD","Excel generate demo with Epplus"),
                            new KeyValuePair<string,string>("DATE_FIELD",$"Date :{System.DateTime.Today.ToString("dd-MMM-yyyy")}"),
                            new KeyValuePair<string,string>("TIME_FIELD",$"Time :{System.DateTime.Now.ToString("hh:mm:ss tt")}"),
                            new KeyValuePair<string,string>("CREATEDBY_FIELD",$"Report generated by : ReportUsername"),
                        };

                var customWidth = Enumerable.Repeat(30, 5).ToArray();
                var result = await _excelGenerateService.GenerateExcelCustomize(
                    Utility.GenerateDatatableWithData(4, 3),
                    displayFields,
                    "GeneratedExcelFile",
                    customWidth
                    );

                return File(result.Attachment, result.MimeType, result.FileName);
            }

            catch (Exception ex)
            {

                var response = new
                {
                    Msg = "Processing request failed.",
                    Errorlst = new List<ErrorMessage>() {
                        new ErrorMessage() { Error = ex.Message } }
                };
                return StatusCode(StatusCodes.Status500InternalServerError, response);
            }
        }
    }
}
